server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  logging:
    level:
      root: DEBUG
      org:
        springframework:
          web: DEBUG
          